FamilyReportBook/FamilyReportBook/Pages/AnswersPage.cshtml.cs
using FamilyReportBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FamilyReportBook.Pages;

public class AnswersPage : PageModel
{
    private readonly ReportBookContext _context;

    public List<Answer> Answers { get; set; } = new();
    public List<AppUser> Users { get; set; } = new();
    [BindProperty(SupportsGet = true)] public int TopicId { get; set; }
    [BindProperty] public NewAnswerDto NewAnswer { get; set; } = new();

    public AnswersPage(ReportBookContext context)
    {
        _context = context;
    }
    
    public async Task<ActionResult> OnGetAsync()
    {
        Answers = await _context.Answers.Where(a => a.TopicId == TopicId)
            .OrderByDescending(a => a.Timestamp)
            .ToListAsync();
        Users = await _context.Users.ToListAsync();
        return Page();
    }

    public async Task<ActionResult> OnPostCreateAnswerAsync()
    {
        await _context.Answers.AddAsync(new Answer
        {
            UserId = NewAnswer.UserId,
            AnsweredToUserId = NewAnswer.AnsweredToUserId,
            Text = NewAnswer.Text,
            Timestamp = DateTime.UtcNow,
            TopicId = NewAnswer.TopicId
        });
        await _context.SaveChangesAsync();
        await OnGetAsync();
        return Page();
    }

    public class NewAnswerDto
    {
        public int UserId { get; set; }
        public int TopicId { get; set; }
        public int AnsweredToUserId { get; set; }
        public string Text { get; set; } = string.Empty;
    }
}

FamilyReportBook/FamilyReportBook/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyReportBook.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

FamilyReportBook/FamilyReportBook/Pages/Index.cshtml.cs
using FamilyReportBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FamilyReportBook.Pages;

public class IndexModel : PageModel
{
    private readonly ReportBookContext _context;
    private readonly ILogger<IndexModel> _logger;

    public List<Topic> Topics { get; set; } = new();
    public List<AppUser> Users { get; set; } = new();
    [BindProperty] public NewTopicDto NewTopic { get; set; }

    public IndexModel(ReportBookContext context, ILogger<IndexModel> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task<ActionResult> OnGetAsync()
    {
        Topics = await _context.Topics.OrderByDescending(t => t.Timestamp).Take(30).ToListAsync();
        Users = await _context.Users.ToListAsync();
        return Page();
    }

    public async Task<ActionResult> OnPostCreateTopicAsync()
    {
        await _context.Topics.AddAsync(new Topic
        {
            Title = NewTopic.Title,
            Timestamp = DateTime.UtcNow,
            LastModified = DateTime.UtcNow,
            Answers = new List<Answer>
            {
                new()
                {
                    Text = NewTopic.Answer,
                    UserId = NewTopic.UserId,
                    AnsweredToUserId = NewTopic.AnsweredTo,
                    Timestamp = DateTime.UtcNow
                }
            }
        });
        await _context.SaveChangesAsync();
        await OnGetAsync();
        return Page();
    }

    public class NewTopicDto
    {
        public string Title { get; set; } = string.Empty;
        public string Answer { get; set; } = string.Empty;
        public int AnsweredTo { get; set; }
        public int UserId { get; set; }
    }
}

FamilyReportBook/FamilyReportBook/Pages/LoginPage.cshtml.cs
using System.Security.Claims;
using FamilyReportBook.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FamilyReportBook.Pages;

public class LoginPage : PageModel
{
    private readonly ReportBookContext _context;

    public LoginState State { get; set; } = LoginState.None;
    public List<AppUser> Users { get; set; } = new();
    [BindProperty] public LoginDto Login { get; set; } = new();

    public LoginPage(ReportBookContext context)
    {
        _context = context;
    }
    
    public async Task<ActionResult> OnGetAsync()
    {
        Users = await _context.Users.ToListAsync();
        return Page();
    }

    public async Task<ActionResult> OnPostLoginAsync()
    {
        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == Login.UserId && u.Password == Login.Password);
        if (user is null)
        {
            await OnGetAsync();
            State = LoginState.Failure;
            return Page();
        }
        
        var claims = new List<Claim>
        {
            new(ClaimTypes.Name, user.FamilyRole.ToString()),
            new(ClaimTypes.NameIdentifier, user.Id.ToString())
        };
        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
            new ClaimsPrincipal(claimsIdentity), new AuthenticationProperties()
                { IsPersistent = Login.RememberMe });
        await OnGetAsync();
        return RedirectToPage("/Index");
    }

    public class LoginDto
    {
        public int UserId { get; set; }
        public string Password { get; set; } = default!;
        public bool RememberMe { get; set; } = true;
    }

    public enum LoginState
    {
        None, Success, Failure
    }
}

FamilyReportBook/FamilyReportBook/Pages/UsersPage.cshtml.cs
using FamilyReportBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FamilyReportBook.Pages;

public class UsersPage : PageModel
{
    private readonly ReportBookContext _context;
    public List<AppUser> Users { get; set; } = new();
    [BindProperty] public NewUserDto NewUser { get; set; } = new();

    public UsersPage(ReportBookContext context)
    {
        _context = context;
    }
    
    public async Task OnGetAsync()
    {
        Users = await _context.Users.ToListAsync();
    }

    public async Task<ActionResult> OnPostCreateUserAsync()
    {
        await _context.Users.AddAsync(new AppUser
        {
            FamilyRole = NewUser.Role,
            Name = NewUser.Name
        });
        await _context.SaveChangesAsync();
        await OnGetAsync();
        return Page();
    }

    public class NewUserDto
    {
        public FamilyRole Role { get; set; } = FamilyRole.None;
        public string Name { get; set; } = default!;
    }
}

FamilyReportBook/FamilyReportBook/Pages/AnswersPage.cshtml
@page "/Topics/{TopicId:int}/Answers"
@model FamilyReportBook.Pages.AnswersPage

@{
    Layout = "Shared/_Layout";
    var i = 1;
}

<div class="accordion mb-2" id="add-answer-accordion">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#add-answer-collapse" aria-expanded="false" aria-controls="add-answer-collapse">
                Cavab əlavə et
            </button>
        </h2>
        <div id="add-answer-collapse" class="accordion-collapse collapse" data-bs-parent="#add-answer-accordion">
            <div class="accordion-body">
                <form method="post">
                    <div class="row">
                        <div class="col-md-2 col-xs-12">
                            <div class="mb-3">
                                <label for="answer-author" class="form-label">Müəllif</label>
                                <select id="answer-author" class="form-select" aria-label="Author selector" required="required" asp-for="NewAnswer.UserId">
                                    <option selected>Müəllif seç</option>
                                    @foreach (var user in Model.Users)
                                    {
                                        <option value="@user.Id">@user.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2 col-xs-12">
                            <div class="mb-3">
                                <label for="answered-to-author" class="form-label">Kimə deyirsiniz?</label>
                                <select id="answered-to-author" class="form-select" aria-label="Author selector" required="required" asp-for="NewAnswer.AnsweredToUserId">
                                    <option selected>Üzv seç</option>
                                    @foreach (var user in Model.Users)
                                    {
                                        <option value="@user.Id">@user.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-8 col-xs-12">
                            <div class="mb-3">
                                <label for="answer-content" class="form-label">Cavab mətni</label>
                                <input type="text" class="form-control" id="answer-content" aria-describedby="answer-content-helper" asp-for="NewAnswer.Text">
                            </div>
                        </div>
                    </div>
                    
                    <input type="hidden" value="@Model.TopicId" asp-for="NewAnswer.TopicId">
                    <button type="submit" class="btn btn-primary" asp-page-handler="CreateAnswer">Əlavə et</button>
                </form>
            </div>
        </div>
    </div>
</div>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Cavab</th>
        <th>Kimdən</th>
        <th>Kimə</th>
        <th>Tarix</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var answer in Model.Answers)
    {
        <tr>
            <td>@(i++)</td>
            <td>@answer.Text</td>
            <td>@answer.User.Name</td>
            <td>@answer.AnsweredToUser.Name</td>
            <td>@answer.Timestamp.ToLocalTime().ToString("dd MMM yyyy, HH:mm")</td>
        </tr>
    }
    </tbody>
</table>

FamilyReportBook/FamilyReportBook/Pages/Index.cshtml
@page
@using FamilyReportBook.Models
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    var i = 1;
}

<h2>Mövzular</h2>
<div class="accordion mb-2" id="add-topic-accordion">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#add-topic-collapse" aria-expanded="false" aria-controls="add-topic-collapse">
                Yeni mövzu üçün tıqla
            </button>
        </h2>
        <div id="add-topic-collapse" class="accordion-collapse collapse" data-bs-parent="#add-topic-accordion">
            <div class="accordion-body">
                <form method="post">
                    <div class="row">
                        <div class="col-md-2 col-xs-12">
                            <div class="mb-3">
                                <label for="topic-author" class="form-label">Müəllif</label>
                                <select id="topic-author" class="form-select" aria-label="Author selector" required="required" asp-for="NewTopic.UserId">
                                    <option selected>Müəllif seç</option>
                                    @foreach (var user in Model.Users)
                                    {
                                        <option value="@user.Id">@user.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-10 col-xs-12">
                            <div class="mb-3">
                                <label for="topic-header" class="form-label">Başlıq</label>
                                <input type="text" class="form-control" id="topic-header" aria-describedby="topic-header-helper" asp-for="NewTopic.Title">
                                <div id="topic-header-helper" class="form-text">Mövzuya başlıq yazın</div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2 col-xs-12">
                            <div class="mb-3">
                                <label for="topic-answer-to" class="form-label">Cavabı verdiyin üzv</label>
                                <select id="topic-answer-to" class="form-select" aria-label="Author selector" required="required" asp-for="NewTopic.AnsweredTo">
                                    <option selected>Üzv seç</option>
                                    @foreach (var user in Model.Users)
                                    {
                                        <option value="@user.Id">@user.Name</option>
                                    }
                                </select>
                            </div>                            
                        </div>
                        <div class="col-md-10 col-xs-12">
                            <div class="mb-3">
                                <label for="topic-answer" class="form-label">Sənin verdiyin cavab</label>
                                <textarea class="form-control" id="topic-answer" rows="3" asp-for="NewTopic.Answer"></textarea>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" asp-page-handler="CreateTopic">Yadda saxla</button>
                </form>
            </div>
        </div>
    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Başlıq</th>
        <th>Yeniləndi</th>
        <th>Keçidlər</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var topic in Model.Topics)
    {
        <tr>
            <th>@(i++)</th>
            <td>@topic.Title</td>
            <td>@topic.LastModified.ToLocalTime().ToString("D")</td>
            <td>
                <a href="@($"/Topics/{topic.Id}/Answers")" class="btn btn-link">Cavablar</a>
            </td>
        </tr>
    }
    </tbody>
</table>

FamilyReportBook/FamilyReportBook/Pages/LoginPage.cshtml
@page
@model FamilyReportBook.Pages.LoginPage

@{
    Layout = "Shared/_Layout";
}

<form method="post">
    <div class="mb-3">
        <label for="name-input" class="form-label">Üzv adı</label>
        <select class="form-select" aria-label="Üzv adı seçimi" id="name-input" asp-for="Login.UserId">
            <option selected>Seçin</option>
            @foreach (var user in Model.Users)
            {
                <option value="@user.Id">@user.Name</option>
            }
        </select>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Şifrə</label>
        <input type="password" class="form-control" id="password" asp-for="Login.Password">
    </div>
    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="remember-me" asp-for="Login.RememberMe">
        <label class="form-check-label" for="remember-me">Məni yadda saxla</label>
    </div>
    
    <button type="submit" class="btn btn-primary" asp-page-handler="Login">Giriş et</button>
</form>

FamilyReportBook/FamilyReportBook/Pages/UsersPage.cshtml
@page "/Users"
@using FamilyReportBook.Models
@model FamilyReportBook.Pages.UsersPage

@{
    Layout = "Shared/_Layout";
    var i = 1;
}

<h2>Ailə üzvləri</h2>

<div class="accordion mb-2" id="add-member-accordion">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#add-member-collapse" aria-expanded="false" aria-controls="add-member-collapse">
                Yeni ailə üzvü üçün tıqla
            </button>
        </h2>
        <div id="add-member-collapse" class="accordion-collapse collapse" data-bs-parent="#add-member-accordion">
            <div class="accordion-body">
                <form method="post">
                    <div class="row">
                        <div class="col-md-2 col-xs-12">
                            <div class="mb-3">
                                <label for="member-role" class="form-label">Üzv rolu</label>
                                <select class="form-select" aria-label="Member role selector" required="required" asp-for="NewUser.Role">
                                    <option selected>Rol seç</option>
                                    <option value="@FamilyRole.Mother">Ana</option>
                                    <option value="@FamilyRole.Father">Ata</option>
                                    <option value="@FamilyRole.Son">Oğul</option>
                                    <option value="@FamilyRole.Doughter">Qız</option>
                                    <option value="@FamilyRole.Grandma">Nənə</option>
                                    <option value="@FamilyRole.Grandpa">Baba</option>
                                    <option value="@FamilyRole.Outsider">Başqası</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-10 col-xs-12">
                            <div class="mb-3">
                                <label for="member-name" class="form-label">Ailə üzvü adı</label>
                                <input type="text" class="form-control" id="member-name" asp-for="NewUser.Name">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" asp-page-handler="CreateUser">Yadda saxla</button>
                </form>
            </div>
        </div>
    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Üzvün rolu</th>
        <th>Adı</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var user in Model.Users)
    {
        <tr>
            <th>@(i++)</th>
            <td>@user.FamilyRole.TranslateTo("az")</td>
            <td>@user.Name</td>
        </tr>
    }
    </tbody>
</table>